name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "danirihani/enterdatawebappapplication"
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: mydatabase
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17.0.12
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.12'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create Docker Hub repository (if it doesn't exist)
      run: |
        curl -s -u ${{ secrets.DOCKERHUB_USERNAME }}:$DOCKERHUB_TOKEN \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{"name": "enterdatawebappapplication", "visibility": "public"}' \
          https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/enterdatawebappapplication

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Verify deployment
      run: |
        sleep 10  # Wait for app to start
        curl --fail http://localhost:8080/health
