name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17.0.12
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.12'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy application
        run: |
          # Pull the latest image
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Stop and remove the existing container if it exists
          docker rm -f webapp-service || true

          # Start a new container with the latest image
          docker run -d --name webapp-service \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL="jdbc:mysql://mysql-db:3306/${{ env.MYSQL_DATABASE }}?useSSL=false" \
            -e SPRING_DATASOURCE_USERNAME=${{ env.MYSQL_USER }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ env.MYSQL_PASSWORD }} \
            --network app-network \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify deployment
        run: |
          sleep 10  # Wait for the application to start
          curl --fail http://localhost:8080/health || exit 1
